version: "3.8"
services:
  btc-rabbitmq:
    image: rabbitmq:3-management
    container_name: btc-rabbitmq
    hostname: btc-rabbitmq
    labels:
      NAME: btc-rabbitmq
    environment:
            RABBITMQ_DEFAULT_USER: fgurdal
            RABBITMQ_DEFAULT_PASS: 123456
    ports: 
       - 5672:5672
       - 15672:15672
    networks:
      - btc-localhost
    restart: always

  btc-postgresql:
    container_name: btc-postgresql
    image: postgres:latest
    ports:
      - 5532:5432
    environment:
      - POSTGRES_PASSWORD=btc12345
      - PGDATA=/data/postgres
      - POSTGRES_DB=btcDb
    volumes:
      - btc-postgresql:/data/postgres
    networks:
      - btc-localhost
    restart: always

  btc-pgadmin:
    container_name: btc-pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: btc12345
    networks:
      - btc-localhost
    restart: always

  btc-webapi:
    container_name: btc-webapi
    image: btc-webapi
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - 12001:5000
    links:
      - btc-postgresql
    depends_on:
      - "btc-postgresql"
      - "btc-rabbitmq"
    networks:
      - btc-localhost
    restart: always
    environment:
      ConnectionStrings:DbConnection: "Server=btc-postgresql;Port=5432;Database=btcDb;User Id=postgres;Password=btc12345"
      ASPNETCORE_ENVIRONMENT: "Development"
      EventBus:HostName: "btc-rabbitmq"
      EventBus:RetryCount: "4"
      EventBus:UserName: "fgurdal"
      EventBus:Password: "123456"
volumes:
    btc-postgresql:

networks:
  btc-localhost:
    driver: bridge